[app]
name = "AI Agent System"
version = "0.1.0"
environment = "production"
debug = false
host = "0.0.0.0"
port = 8080

[database]
url = "postgresql://localhost/ai_agent_prod"
max_connections = 50
min_connections = 10
connection_timeout = 30
idle_timeout = 300
max_lifetime = 3600

[redis]
url = "redis://localhost:6379"
pool_size = 20
connection_timeout = 5
read_timeout = 3
write_timeout = 3

[http]
cors_origins = []
rate_limit_requests = 100
rate_limit_window = 3600
request_timeout = 30
max_body_size = 10485760

[security]
jwt_secret = "production-secret-key-must-be-set-via-env"
jwt_expiration = 86400
bcrypt_cost = 12
api_key_required = true
encryption_enabled = true
allowed_ips = []

[logging]
level = "info"
format = "json"
output = "file"
file_path = "/var/log/ai-agent/app.log"
max_file_size = 104857600
max_files = 30

[machine_learning]
model_cache_size = 1000
training_timeout = 7200
inference_timeout = 60
gpu_enabled = true
model_update_interval = 86400

[plugins]
plugin_directory = "/opt/ai-agent/plugins"
auto_load = false
sandbox_enabled = true
max_plugin_memory = 524288000
